// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4CTz5i34_t_ds3jA0J22UVBWIQYsRlWc',
    appId: '1:1083783968222:web:281ba52099f13f7a63194f',
    messagingSenderId: '1083783968222',
    projectId: 'codingo-app-2d385',
    authDomain: 'codingo-app-2d385.firebaseapp.com',
    storageBucket: 'codingo-app-2d385.appspot.com',
    measurementId: 'G-SDHRL55LGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQq2YfhcOv7Wxi--cb_1WZ4-CPiQQ6pX0',
    appId: '1:1083783968222:android:23b73f7a7b2c888563194f',
    messagingSenderId: '1083783968222',
    projectId: 'codingo-app-2d385',
    storageBucket: 'codingo-app-2d385.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKwKwiNoEDaFRO2e9v23E58eFxwewAoUY',
    appId: '1:1083783968222:ios:42e2ae5e65a148a763194f',
    messagingSenderId: '1083783968222',
    projectId: 'codingo-app-2d385',
    storageBucket: 'codingo-app-2d385.appspot.com',
    iosClientId: '1083783968222-nbe7oud9269bbhq6am5cd31ao3bkhap8.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKwKwiNoEDaFRO2e9v23E58eFxwewAoUY',
    appId: '1:1083783968222:ios:ba00c75537813d0f63194f',
    messagingSenderId: '1083783968222',
    projectId: 'codingo-app-2d385',
    storageBucket: 'codingo-app-2d385.appspot.com',
    iosClientId: '1083783968222-a6bjq56dj5c8jj6lkjloneadtakq8lfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingo.RunnerTests',
  );
}
